from pathlib import Path
import re

root = Path('.')
site = root / 'site'
old_shared = site / 'modules/core-sources/shared.js'
new_shared = site / 'modules/core-sources/shared-shell-navigation.js'
assert old_shared.exists() and not new_shared.exists()
source = old_shared.read_text()
assert source.startswith(';(() => {\n  if (window.__mflFooterSpaNavigationBound) return;')
assert '.siteFooterDetails a[href="/changelog"]' in source
assert '.changelogMinorToggle' in source
assert '.brandLink[href="/"]' in source
old_shared.rename(new_shared)

old_banner = '// Generated by build-app-core.mjs from modules/core-sources/shared.js. Do not edit directly.\\n'
new_banner = '// Generated Shared core by build-app-core.mjs from the canonical source manifest. Do not edit directly.\\n'

manifest_path = site / 'modules/core-source-manifest.js'
text = manifest_path.read_text()
assert text.count('"shared-app-startup.js", "shared.js"') == 1
assert text.count(old_banner) == 1
text = text.replace('"shared-app-startup.js", "shared.js"', '"shared-app-startup.js", "shared-shell-navigation.js"')
text = text.replace(old_banner, new_banner)
manifest_path.write_text(text)

check_types = site / 'check-core-types.mjs'
text = check_types.read_text()
assert text.count('"modules/core-sources/shared.js:TS2339": 71') == 1
assert text.count('"modules/core-sources/shared.js:TS2630": 23') == 1
text = text.replace('"modules/core-sources/shared.js:TS2339": 71', '"modules/core-sources/shared-shell-navigation.js:TS2339": 71')
text = text.replace('"modules/core-sources/shared.js:TS2630": 23', '"modules/core-sources/shared-shell-navigation.js:TS2630": 23')
check_types.write_text(text)

for path, old_ref, new_ref in [
    (site / 'validate.mjs', 'sharedCoreManifest.sources[27] === "shared.js"', 'sharedCoreManifest.sources[27] === "shared-shell-navigation.js"'),
    (site / 'validate-club-route-core.mjs', 'coreSourceByDomain.shared.sources[27] === "shared.js"', 'coreSourceByDomain.shared.sources[27] === "shared-shell-navigation.js"'),
]:
    text = path.read_text()
    assert text.count(old_ref) == 1
    path.write_text(text.replace(old_ref, new_ref).replace('before remaining shared behavior', 'before shell-navigation bindings'))

ownership = site / 'validate-core-source-ownership.mjs'
text = ownership.read_text()
assert text.count('sharedEntry.sources[27] === "shared.js"') == 1
assert text.count('const sharedRemaining = await read("./modules/core-sources/shared.js");') == 1
text = text.replace('sharedEntry.sources[27] === "shared.js"', 'sharedEntry.sources[27] === "shared-shell-navigation.js"')
text = text.replace('const sharedRemaining = await read("./modules/core-sources/shared.js");', 'const sharedShellNavigation = await read("./modules/core-sources/shared-shell-navigation.js");')
text = text.replace('sharedRemaining', 'sharedShellNavigation')
needle = 'sharedShellNavigation.startsWith(";(() => {\\n  if (window.__mflFooterSpaNavigationBound) return;")\n    && !sharedShellNavigation.includes("__mflUniversalClubSearch")'
replacement = 'sharedShellNavigation.startsWith(";(() => {\\n  if (window.__mflFooterSpaNavigationBound) return;")\n    && sharedShellNavigation.includes(\'.siteFooterDetails a[href="/changelog"]\')\n    && sharedShellNavigation.includes(".changelogMinorToggle")\n    && sharedShellNavigation.includes(\'.brandLink[href="/"]\')\n    && !sharedShellNavigation.includes("__mflUniversalClubSearch")'
assert text.count(needle) == 1
text = text.replace(needle, replacement)
text = text.replace('"Remaining Shared behavior must begin at global shell-navigation bindings after application startup publication."', '"Shared shell navigation must own footer Changelog navigation/toggling and brand Home navigation after application startup publication."')
text = text.replace('before application startup before remaining shared behavior', 'before application startup before shell navigation')
text = text.replace('and application startup must not absorb later ownership domains.', 'application startup, and shell navigation must keep explicit terminal ownership boundaries.')
ownership.write_text(text)

for filename in [
    'validate-app-core-startup-handshake.mjs',
    'validate-club-title-loading.mjs',
    'validate-evaluation-route-ownership.mjs',
]:
    path = site / filename
    text = path.read_text()
    assert text.count(old_banner) == 1, filename
    path.write_text(text.replace(old_banner, new_banner))

# Custom validators that still assembled physical core-file lists.
path = site / 'validate-progression-sorting.mjs'
text = path.read_text()
assert 'import fs from "node:fs";\n' in text
assert '"./modules/core-sources/shared.js",' in text
text = text.replace('import fs from "node:fs";\n', '')
text = text.replace('import { DatabaseSync } from "node:sqlite";\n', 'import { DatabaseSync } from "node:sqlite";\nimport { readCombinedCanonicalCoreSource } from "./validate-core-sources.mjs";\n')
text, count = re.subn(r'const core = \[\n(?:  "\./modules/core-sources/[^\n]+",\n)+\]\.map\(\(path\) => fs\.readFileSync\(new URL\(path, import\.meta\.url\), "utf8"\)\)\.join\("\\n"\);', 'const core = readCombinedCanonicalCoreSource();', text)
assert count == 1
path.write_text(text)

path = site / 'validate-evaluation-saved-share-icon.mjs'
text = path.read_text()
assert 'modules/core-sources/shared.js' in text
text = text.replace('import { fileURLToPath } from "node:url";\n', 'import { fileURLToPath } from "node:url";\nimport { readCombinedCanonicalCoreSource } from "./validate-core-sources.mjs";\n')
text, count = re.subn(r'const canonicalCore = await Promise\.all\(\[\n(?:    readFile\(join\(siteRoot, "modules/core-sources/[^\n]+\), "utf8"\),\n)+  \]\)\.then\(\(parts\) => parts\.join\("\\n"\)\);', 'const canonicalCore = readCombinedCanonicalCoreSource();', text)
assert count == 1
path.write_text(text)

path = site / 'validate-stats-mobile-scaling.mjs'
text = path.read_text()
assert '"modules/core-sources/shared.js",' in text
text = text.replace('import { fileURLToPath } from "node:url";\n', 'import { fileURLToPath } from "node:url";\nimport { readCombinedCanonicalCoreSource } from "./validate-core-sources.mjs";\n')
text, count = re.subn(r'const appCore = \[\n(?:  "modules/core-sources/[^\n]+",\n)+\]\.map\(read\)\.join\("\\n"\);', 'const appCore = readCombinedCanonicalCoreSource();', text)
assert count == 1
path.write_text(text)

path = site / 'validate-z-index-ownership.mjs'
text = path.read_text()
assert 'modules/core-sources/shared.js' in text
text = text.replace('import { fileURLToPath } from "node:url";\n', 'import { fileURLToPath } from "node:url";\nimport { readCombinedCanonicalCoreSource } from "./validate-core-sources.mjs";\n')
text, count = re.subn(r'const canonicalCore = await Promise\.all\(\[\n(?:    readFile\(join\(siteRoot, "modules/core-sources/[^\n]+\), "utf8"\),\n)+  \]\)\.then\(\(parts\) => parts\.join\("\\n"\)\);', 'const canonicalCore = readCombinedCanonicalCoreSource();', text)
assert count == 1
path.write_text(text)

arch = root / 'docs/architecture-guardrails.md'
text = arch.read_text()
assert '`site/modules/core-sources/shared.js` may not exceed **355,000 UTF-8 bytes**' in text
assert '`shared.js` is universal code.' in text
text = text.replace('`site/modules/core-sources/shared.js` may not exceed **355,000 UTF-8 bytes**', 'the manifest-assembled Shared domain may not exceed **355,000 UTF-8 bytes**')
text = text.replace('`shared.js` is universal code. Growth there affects every route and can silently pull route-specific responsibilities back into the common runtime.', 'the assembled Shared domain is universal code. Growth anywhere in its manifest-owned fragments affects every route and can silently pull route-specific responsibilities back into the common runtime.')
arch.write_text(text)

ownership_doc = root / 'docs/ownership.md'
lines = ownership_doc.read_text().splitlines()
index = next(i for i, line in enumerate(lines) if line.startswith('- `site/modules/core-sources/shared-foundations.js` owns'))
lines[index] = '- The Shared domain is source-decomposed into manifest-ordered responsibilities: `shared-foundations.js` (state/constants/DOM), `shared-session.js` (theme/account/session), `shared-routing.js` (route parsing/paths), `shared-transitions.js` (page/view transitions), `shared-page-lifecycle.js` (stable page/Table facades and base rendering), `shared-home-summary.js`, `shared-table-state.js`, `shared-toast-core.js`, `shared-personal-state.js`, `shared-data-search.js`, `shared-evaluation-lifecycle.js`, `shared-player-first-paint.js`, `shared-watchlist-actions.js`, `shared-player-display.js`, `shared-player-actions.js`, `shared-modal-lifecycle.js`, `shared-global-search.js`, `shared-wallet-row-classification.js`, `shared-html-escaping.js`, `shared-incremental-routing.js`, `shared-interaction-bindings.js`, `shared-startup-lifecycle.js`, `shared-layout-center.js`, `shared-incremental-navigation.js`, `shared-route-runtime-gate.js`, `shared-core-contracts.js`, `shared-app-startup.js`, and terminal `shared-shell-navigation.js`. These fragments are lexical source boundaries only: the manifest assembles them in order into the single `app-core-runtime.js` browser payload, so they add no browser requests. Behavioral validators must consume assembled Shared through `validate-core-sources.mjs`; direct physical-fragment reads are reserved for explicit ownership-boundary assertions. Lexical splits move TypeScript diagnostic buckets with their physical owner and may not increase aggregate debt. The assembled Shared domain retains the 355,000-byte universal ceiling; route/domain sources are split by responsibility, readability, testability, or route cost rather than arbitrary byte limits.'
ownership_doc.write_text('\n'.join(lines) + '\n')

# The legacy filename must be fully retired outside the not-yet-regenerated artifact and temporary task files.
for path in root.rglob('*'):
    if not path.is_file():
        continue
    rel = path.as_posix()
    if rel == 'site/modules/app-core-runtime.js' or rel.startswith('.github/'):
        continue
    try:
        data = path.read_text()
    except UnicodeDecodeError:
        continue
    assert 'shared.js' not in data, f'Legacy shared.js reference remains in {rel}'

print('Retired physical shared.js; final Shared fragment is shared-shell-navigation.js')
